# Generated by Django 2.1.4 on 2021-09-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminOperateRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operate_type', models.SmallIntegerField(choices=[(0, '添加'), (1, '编辑'), (2, '删除')], default=0, verbose_name='类型')),
                ('module', models.CharField(max_length=255, verbose_name='模块')),
                ('record_sign', models.CharField(max_length=255, null=True, verbose_name='记录标记')),
                ('new_data', models.TextField(null=True, verbose_name='数据')),
                ('comment', models.CharField(max_length=255, null=True, verbose_name='操作备注')),
                ('user_id', models.IntegerField(null=True, verbose_name='操作用户')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '操作记录',
                'verbose_name_plural': '操作记录',
                'db_table': 'operate_admin_record',
            },
        ),
        migrations.CreateModel(
            name='NotifyMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_read', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0)),
                ('module', models.CharField(max_length=255, null=True, verbose_name='模块')),
                ('record_sign', models.CharField(max_length=255, null=True, verbose_name='记录标记')),
                ('tenant_id', models.IntegerField(null=True)),
                ('user_id', models.IntegerField(null=True)),
                ('create_user_id', models.IntegerField(null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '消息通知表',
                'verbose_name_plural': '消息通知表',
                'db_table': 'user_notify_message',
            },
        ),
    ]
