# Generated by Django 2.1.4 on 2021-09-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='仓库名称')),
                ('code', models.CharField(max_length=32, null=True, verbose_name='仓库编号')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='仓库地址')),
                ('manager_id', models.IntegerField(null=True, verbose_name='负责人id')),
                ('reserve', models.CharField(max_length=255, null=True)),
                ('is_delete', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('create_user_id', models.IntegerField(null=True)),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('update_user_id', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': '仓库表',
                'verbose_name_plural': '仓库表',
                'db_table': 'warehouse',
            },
        ),
    ]
