# Generated by Django 2.1.4 on 2021-09-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, null=True, verbose_name='产品编号')),
                ('name', models.CharField(max_length=255, verbose_name='产品名称')),
                ('spec', models.CharField(max_length=255, null=True, verbose_name='规格')),
                ('category_id', models.IntegerField(null=True, verbose_name='分类id')),
                ('delivery_place', models.CharField(max_length=255, null=True, verbose_name='提货地')),
                ('steel_mill', models.CharField(max_length=64, null=True, verbose_name='钢厂')),
                ('heat_number', models.CharField(max_length=64, null=True, verbose_name='炉号')),
                ('unit', models.CharField(max_length=11, null=True, verbose_name='单位')),
                ('img', models.TextField(null=True, verbose_name='图片')),
                ('reserve', models.CharField(max_length=255, null=True)),
                ('is_delete', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('create_user_id', models.IntegerField(null=True)),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('update_user_id', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': '产品信息表',
                'verbose_name_plural': '产品信息表',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='类型名称')),
                ('parent_id', models.IntegerField(null=True, verbose_name='父级id')),
                ('is_delete', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('create_user_id', models.IntegerField(null=True)),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('update_user_id', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': '产品类型表',
                'verbose_name_plural': '产品类型表',
                'db_table': 'product_category',
            },
        ),
    ]
